### ISSUE TITLE
Audio volume notification bar doesn't appear

### ISSUE THREAD

**Issue by kafran** [BunsenLabs/bunsen-netinstall#17]
As noted by @johnraff the [audio volume notification bar is not appearing](https://forums.bunsenlabs.org/viewtopic.php?pid=51365#p51365) within Helium-dev. On Deuterium this works on both machine tested. I think this is because the change from "volti" to "volumeicon". Also, I would like to suggest bunsenlabs packages to be installed with "no recommends" on Helium-dev.

**Comment by johnraff** [comment]
In fact the "Deuterium" upgrade of BunsenLabs Hydrogen is already using volumeicon instead of volti (this fixes a different issue) and there is no problem with the volume bars, as you noted.

Something has changed with Debian Stretch. We are also considering using pnmixer instead of volumeicon-alsa in Helium-dev.

> Also, I would like to suggest bunsenlabs packages to be installed with "no recommends" on Helium-dev.

At present, since we ourselves are deciding the "Recommends" of BunsenLabs packages, and choosing packages which we consider important for the setup, there is no reason for the netinstall script not to install them. Users with special needs are free to cherry-pick the BL packages they want. If there are any specific packages which you think should not be Recommends of a BL package, please post a separate issue.

**Comment by kafran** [comment]
> We are also considering using pnmixer instead of volumeicon-alsa in Helium-dev

Nice. I installed PNMixer here and notification works.

**Comment by johnraff** [comment]
BunsenLabs Helium now uses pnmixer, and I think this issue can be closed.
