### ISSUE TITLE
undo/install doesn't handle local sources list

### ISSUE THREAD

**Issue by maricn** [BunsenLabs/bunsen-netinstall#2]
My installation broke due to insufficient root fs size in process of serting up

**Comment by maricn** [comment]
My installation broke due to insufficient fs size in process of setting up bunsen-images. I had to manually remove local souces list from /etc/apt/.. to be able to run install script again.

**Comment by johnraff** [comment]
Hi maricn, thank you for reporting this.

bunsen-images is very big - about 100MB - so will need plenty of space for building, but the install script has run successfully for others. It is intended as a development tool, rather than an install vehicle for end-users. (That will come later.)

The "undo" script is _very_ experimental and hasn't been tested in the BunsenLabs context. It was simply imported from a previous installer: https://github.com/johnraff/cb-netinstall

It might help if the image files of bunsen-images are packed into a tarball in the Debian source repository, in the same way as with bunsen-faenza-icon-theme. When I have time, I'll try that.

**Comment by maricn** [comment]
Oh, i didn't realize undo wasn't yours script. Anyway, just thought you should know about that.

Thumbs up for quick answer and effort on the project.

**Comment by johnraff** [comment]
Yes _undo_ is my script but I haven't tested it with BunsenLabs. Even in it's previous home it was still quite experimental. I just imported it with everything else, thinking I might work on it some day...

Thank you for your input anyway. I'll need to think about the local repos - they didn't exist in the previous installer.

**Comment by johnraff** [comment]
Git requires as much free space on your disk as in the repository, which might be the reason upacking bunsen-images caused problems. I have now packed all the image files into a .tar.gz archive which might reduce the download time slightly, but I'm not sure if it will help the installation problem.

**Comment by johnraff** [comment]
Experimental _undo_ script removed.
