### ISSUE TITLE
Offer free software only (libre) variant of the netinstaller.

### ISSUE THREAD

**Issue by JeffreyAbbinante** [BunsenLabs/bunsen-netinstall#21]
Over the past couple of weeks, I have been testing the viability of using the BunsenLabs distribution with a computer designed to run all free software (Libreboot X200). Although I prefer XFCE, the experience was very responsive and felt complete. This would make a great option for a person who needs a quick to setup GNU/Linux computer that ran only free software. I did however notice that some non-free software is included with the release. I went ahead and created a netinstaller that did not load non-free software by default. It worked perfectly. I also forked the welcome script to no longer suggest non-free software and even added https support. These forks can be found on my [GitHub](https://github.com/JeffreyAbbinante?tab=repositories) page. Here is what is left to do in order to make a "libre" version of BunsenLabs:
- Package the "libre" netinstaller.
- Package the "libre" welcome script and set the "libre" netinstaller to use it as default.
- Change the openbox menu configuration to not suggest installing non-free software such as Google Chrome and include that with the "libre" netinstaller.
- Offer it on the BunsenLabs website as an alternative installation option.

I think this would be a great option for BunsenLabs to include. I made a post on [Reddit](https://www.reddit.com/r/debian/comments/a8hwri/need_testers_for_my_dfsgcompliant_variant_of/) and there seems to be some demand for this type of distribution. Besides I already did most of the work! I look forward to potentially working with the BunsenLabs team on this.

**Comment by johnraff** [comment]
Hello @JeffreyAbbinante, 
thank you for your interest in BunsenLabs, and for taking the time to improve it!

The dev team have considered your suggestion with interest, and right now we are thinking about what would be the best way to accomodate installers who want a 100% libre system. BunsenLabs basically inherits from CrunchBang a rather pragmatic approach to proprietary firmware, in that most machines require it in order to operate well, and the BL desktop is intended to work out of the box for less experienced users.

Right now I'm considering adding a "libre" option to the netinstall script (which I maintain). Other possibilities would be a post-install script to remove non-free packages, or a forum HOW-TO. Anyway, once the Debian Buster transition (our current top priority) is dealt with, we'll revisit this issue.

Meanwhile, you are of course free to make a libre version of the netinstall script and associated files, and thanks again for your interest!

John

**Comment by johnraff** [comment]
The issue of firmware with modern hardware gets more and more difficult. The Debian developers themselves are still grappling with the situation: https://blog.einval.com/2022/04/19#firmware-what-do-we-do

While I agree about the importance of free software, I don't think the potential user base for a completely libre BunsenLabs system justifies right now the developer time needed to create and maintain it, especially while the situation at Debian is so fluid.
